### PR TITLE
Implement go mod

### PR DESCRIPTION
**Pull request by pizzatarian**
* [x] Implements Go mod
* [x] Removes Godep
* [x] Updates README.md

### CODE REVIEW

**Comment by 0x13a** [comment]
if https://github.com/lightstreams-network/lightchain/pull/140/files gets merged first we may need to re-run go mod vendor and pull back the latest version of geth

**Comment by EnchanterIO** [comment]
This task also requires to upgrade all of our docker images to new Go version 1.11 

FYI: @iris-garcia @ggarri

**Comment by 0x13a** [comment]
yes, thanks for the heads-up. I've forgotten the dockerfile.

**Comment by EnchanterIO** [comment]
Thx for updating it! In the comment about docker images I was just leaving a note for myself actually, referring to our infrastructure :)

Diego, do you think is worth it to update directly to go 1.12?

**Comment by 0x13a** [comment]
yes, probably worth it if it doesn't break any deps

**Comment by 0x13a** [comment]
I've run it on my machine but can you please try before merging if `make docker` works as expected? everything's fine on my machine

**Pull request closed without merging**
